In [1]:
import numpy as np

In [3]:
it = [3, 6, 7, 11]

In [4]:
n = np.array(it)

In [5]:
type(n)

numpy.ndarray

In [26]:
twod = np.array([[1,2], [3,4,]])

twod.size


4

In [17]:
y = np.array([2,3,4, "13"])


In [18]:
y

array(['2', '3', '4', '13'], dtype='<U11')

In [22]:
n.shape

(4,)

In [38]:
list(range(9, 22, 3))

[9, 12, 15, 18, 21]

In [39]:
np.arange(8 , 40, 5)

array([ 8, 13, 18, 23, 28, 33, 38])

In [41]:
np.array

<function numpy.array>

In [62]:
arr1 = np.arange(20)

In [63]:
arr2 = arr1.reshape(5, 4)

In [64]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [65]:
arr1[0] = 90

In [66]:
arr2

array([[90,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [67]:
arr1 is arr2

False